// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file yeying/api/common/model.proto (package yeying.api.common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ApiCodeEnum, ApplicationCodeEnum, ServiceCodeEnum } from "./code_pb";
import { file_yeying_api_common_code } from "./code_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yeying/api/common/model.proto.
 */
export const file_yeying_api_common_model: GenFile = /*@__PURE__*/
  fileDesc("Ch15ZXlpbmcvYXBpL2NvbW1vbi9tb2RlbC5wcm90bxIReWV5aW5nLmFwaS5jb21tb24i4AIKE0FwcGxpY2F0aW9uTWV0YWRhdGESDQoFb3duZXIYASABKAkSDwoHbmV0d29yaxgCIAEoCRIPCgdhZGRyZXNzGAMgASgJEgsKA2RpZBgEIAEoCRIPCgd2ZXJzaW9uGAUgASgNEgwKBGhhc2gYBiABKAkSDAoEbmFtZRgHIAEoCRI0CgRjb2RlGAggASgOMiYueWV5aW5nLmFwaS5jb21tb24uQXBwbGljYXRpb25Db2RlRW51bRITCgtkZXNjcmlwdGlvbhgJIAEoCRIQCghsb2NhdGlvbhgKIAEoCRI4CgxzZXJ2aWNlQ29kZXMYCyADKA4yIi55ZXlpbmcuYXBpLmNvbW1vbi5TZXJ2aWNlQ29kZUVudW0SDgoGYXZhdGFyGAwgASgJEhEKCWNyZWF0ZWRBdBgNIAEoCRIRCgl1cGRhdGVkQXQYDiABKAkSEQoJc2lnbmF0dXJlGA8gASgJIs0CCg9TZXJ2aWNlTWV0YWRhdGESDQoFb3duZXIYASABKAkSDwoHbmV0d29yaxgCIAEoCRIPCgdhZGRyZXNzGAMgASgJEgsKA2RpZBgEIAEoCRIPCgd2ZXJzaW9uGAUgASgNEgwKBG5hbWUYBiABKAkSEwoLZGVzY3JpcHRpb24YByABKAkSMAoEY29kZRgIIAEoDjIiLnlleWluZy5hcGkuY29tbW9uLlNlcnZpY2VDb2RlRW51bRIwCghhcGlDb2RlcxgJIAMoDjIeLnlleWluZy5hcGkuY29tbW9uLkFwaUNvZGVFbnVtEg0KBXByb3h5GAogASgJEgwKBGdycGMYCyABKAkSDgoGYXZhdGFyGAwgASgJEhEKCWNyZWF0ZWRBdBgNIAEoCRIRCgl1cGRhdGVkQXQYDiABKAkSEQoJc2lnbmF0dXJlGA8gASgJQhNaEXlleWluZy9hcGkvY29tbW9uYgZwcm90bzM", [file_yeying_api_common_code]);

/**
 * @generated from message yeying.api.common.ApplicationMetadata
 */
export type ApplicationMetadata = Message<"yeying.api.common.ApplicationMetadata"> & {
  /**
   * 应用所有者 
   *
   * @generated from field: string owner = 1;
   */
  owner: string;

  /**
   * 身份所在网络 
   *
   * @generated from field: string network = 2;
   */
  network: string;

  /**
   * 身份地址 
   *
   * @generated from field: string address = 3;
   */
  address: string;

  /**
   * 应用身份 
   *
   * @generated from field: string did = 4;
   */
  did: string;

  /**
   * 应用版本 
   *
   * @generated from field: uint32 version = 5;
   */
  version: number;

  /**
   * 应用哈希 
   *
   * @generated from field: string hash = 6;
   */
  hash: string;

  /**
   * 应用名称 
   *
   * @generated from field: string name = 7;
   */
  name: string;

  /**
   * 应用编号 
   *
   * @generated from field: yeying.api.common.ApplicationCodeEnum code = 8;
   */
  code: ApplicationCodeEnum;

  /**
   * 应用描述 
   *
   * @generated from field: string description = 9;
   */
  description: string;

  /**
   * 访问路径 
   *
   * @generated from field: string location = 10;
   */
  location: string;

  /**
   * 应用依赖的服务编码，用,隔开 
   *
   * @generated from field: repeated yeying.api.common.ServiceCodeEnum serviceCodes = 11;
   */
  serviceCodes: ServiceCodeEnum[];

  /**
   * 应用头像 
   *
   * @generated from field: string avatar = 12;
   */
  avatar: string;

  /**
   * 应用创建时间 
   *
   * @generated from field: string createdAt = 13;
   */
  createdAt: string;

  /**
   * 应用更新时间 
   *
   * @generated from field: string updatedAt = 14;
   */
  updatedAt: string;

  /**
   * 签名
   *
   * @generated from field: string signature = 15;
   */
  signature: string;
};

/**
 * Describes the message yeying.api.common.ApplicationMetadata.
 * Use `create(ApplicationMetadataSchema)` to create a new message.
 */
export const ApplicationMetadataSchema: GenMessage<ApplicationMetadata> = /*@__PURE__*/
  messageDesc(file_yeying_api_common_model, 0);

/**
 * @generated from message yeying.api.common.ServiceMetadata
 */
export type ServiceMetadata = Message<"yeying.api.common.ServiceMetadata"> & {
  /**
   * 服务所有者 
   *
   * @generated from field: string owner = 1;
   */
  owner: string;

  /**
   * 服务所在网络 
   *
   * @generated from field: string network = 2;
   */
  network: string;

  /**
   * 服务所在网络地址 
   *
   * @generated from field: string address = 3;
   */
  address: string;

  /**
   * 服务身份 
   *
   * @generated from field: string did = 4;
   */
  did: string;

  /**
   * 服务版本 
   *
   * @generated from field: uint32 version = 5;
   */
  version: number;

  /**
   * 服务名称 
   *
   * @generated from field: string name = 6;
   */
  name: string;

  /**
   * 服务描述 
   *
   * @generated from field: string description = 7;
   */
  description: string;

  /**
   * 服务编码 
   *
   * @generated from field: yeying.api.common.ServiceCodeEnum code = 8;
   */
  code: ServiceCodeEnum;

  /**
   * 服务apis 
   *
   * @generated from field: repeated yeying.api.common.ApiCodeEnum apiCodes = 9;
   */
  apiCodes: ApiCodeEnum[];

  /**
   * 服务代理 
   *
   * @generated from field: string proxy = 10;
   */
  proxy: string;

  /**
   * 服务grpc地址 
   *
   * @generated from field: string grpc = 11;
   */
  grpc: string;

  /**
   * 服务头像 
   *
   * @generated from field: string avatar = 12;
   */
  avatar: string;

  /**
   * 服务创建时间点 
   *
   * @generated from field: string createdAt = 13;
   */
  createdAt: string;

  /**
   * 服务修改时间点 
   *
   * @generated from field: string updatedAt = 14;
   */
  updatedAt: string;

  /**
   * 签名
   *
   * @generated from field: string signature = 15;
   */
  signature: string;
};

/**
 * Describes the message yeying.api.common.ServiceMetadata.
 * Use `create(ServiceMetadataSchema)` to create a new message.
 */
export const ServiceMetadataSchema: GenMessage<ServiceMetadata> = /*@__PURE__*/
  messageDesc(file_yeying_api_common_model, 1);

