// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file yeying/api/apps/zuoyepigai/homework.proto (package yeying.api.apps.zuoyepigai, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { MessageHeader, ResponseStatus } from "../../common/message_pb";
import { file_yeying_api_common_message } from "../../common/message_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yeying/api/apps/zuoyepigai/homework.proto.
 */
export const file_yeying_api_apps_zuoyepigai_homework: GenFile = /*@__PURE__*/
  fileDesc("Cil5ZXlpbmcvYXBpL2FwcHMvenVveWVwaWdhaS9ob21ld29yay5wcm90bxIaeWV5aW5nLmFwaS5hcHBzLnp1b3llcGlnYWkiigEKE0hvbWV3b3JrTGlzdFJlcXVlc3QSMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchJBCgRib2R5GAIgASgLMjMueWV5aW5nLmFwaS5hcHBzLnp1b3llcGlnYWkuSG9tZXdvcmtMaXN0UmVxdWVzdEJvZHkiJgoXSG9tZXdvcmtMaXN0UmVxdWVzdEJvZHkSCwoDZGlkGAEgASgJIowBChRIb21ld29ya0xpc3RSZXNwb25zZRIwCgZoZWFkZXIYASABKAsyIC55ZXlpbmcuYXBpLmNvbW1vbi5NZXNzYWdlSGVhZGVyEkIKBGJvZHkYAiABKAsyNC55ZXlpbmcuYXBpLmFwcHMuenVveWVwaWdhaS5Ib21ld29ya0xpc3RSZXNwb25zZUJvZHkiiQEKGEhvbWV3b3JrTGlzdFJlc3BvbnNlQm9keRIxCgZzdGF0dXMYASABKAsyIS55ZXlpbmcuYXBpLmNvbW1vbi5SZXNwb25zZVN0YXR1cxI6CgRsaXN0GAIgAygLMiwueWV5aW5nLmFwaS5hcHBzLnp1b3llcGlnYWkuSG9tZXdvcmtNZXRhZGF0YSKMAQoQSG9tZXdvcmtNZXRhZGF0YRILCgN1aWQYASABKAkSCwoDZGlkGAIgASgJEg8KB3N1YmplY3QYAyABKAkSFAoMdGVzdFBhcGVyVWlkGAQgASgJEhEKCWNyZWF0ZWRBdBgFIAEoAxIRCgl1cGRhdGVkQXQYBiABKAMSEQoJaXNEZWxldGVkGAcgASgIIo4BChVIb21ld29ya0RldGFpbFJlcXVlc3QSMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchJDCgRib2R5GAIgASgLMjUueWV5aW5nLmFwaS5hcHBzLnp1b3llcGlnYWkuSG9tZXdvcmtEZXRhaWxSZXF1ZXN0Qm9keSIoChlIb21ld29ya0RldGFpbFJlcXVlc3RCb2R5EgsKA3VpZBgBIAEoCSKQAQoWSG9tZXdvcmtEZXRhaWxSZXNwb25zZRIwCgZoZWFkZXIYASABKAsyIC55ZXlpbmcuYXBpLmNvbW1vbi5NZXNzYWdlSGVhZGVyEkQKBGJvZHkYAiABKAsyNi55ZXlpbmcuYXBpLmFwcHMuenVveWVwaWdhaS5Ib21ld29ya0RldGFpbFJlc3BvbnNlQm9keSKLAQoaSG9tZXdvcmtEZXRhaWxSZXNwb25zZUJvZHkSMQoGc3RhdHVzGAEgASgLMiEueWV5aW5nLmFwaS5jb21tb24uUmVzcG9uc2VTdGF0dXMSOgoEbWV0YRgCIAEoCzIsLnlleWluZy5hcGkuYXBwcy56dW95ZXBpZ2FpLkhvbWV3b3JrTWV0YWRhdGEy6gEKCEhvbWV3b3JrEmsKBExpc3QSLy55ZXlpbmcuYXBpLmFwcHMuenVveWVwaWdhaS5Ib21ld29ya0xpc3RSZXF1ZXN0GjAueWV5aW5nLmFwaS5hcHBzLnp1b3llcGlnYWkuSG9tZXdvcmtMaXN0UmVzcG9uc2UiABJxCgZEZXRhaWwSMS55ZXlpbmcuYXBpLmFwcHMuenVveWVwaWdhaS5Ib21ld29ya0RldGFpbFJlcXVlc3QaMi55ZXlpbmcuYXBpLmFwcHMuenVveWVwaWdhaS5Ib21ld29ya0RldGFpbFJlc3BvbnNlIgBCHFoaeWV5aW5nL2FwaS9hcHBzL3p1b3llcGlnYWliBnByb3RvMw", [file_yeying_api_common_message]);

/**
 * 列表
 *
 * @generated from message yeying.api.apps.zuoyepigai.HomeworkListRequest
 */
export type HomeworkListRequest = Message<"yeying.api.apps.zuoyepigai.HomeworkListRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.apps.zuoyepigai.HomeworkListRequestBody body = 2;
   */
  body?: HomeworkListRequestBody;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.HomeworkListRequest.
 * Use `create(HomeworkListRequestSchema)` to create a new message.
 */
export const HomeworkListRequestSchema: GenMessage<HomeworkListRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_homework, 0);

/**
 * @generated from message yeying.api.apps.zuoyepigai.HomeworkListRequestBody
 */
export type HomeworkListRequestBody = Message<"yeying.api.apps.zuoyepigai.HomeworkListRequestBody"> & {
  /**
   * 学生ID
   *
   * @generated from field: string did = 1;
   */
  did: string;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.HomeworkListRequestBody.
 * Use `create(HomeworkListRequestBodySchema)` to create a new message.
 */
export const HomeworkListRequestBodySchema: GenMessage<HomeworkListRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_homework, 1);

/**
 * @generated from message yeying.api.apps.zuoyepigai.HomeworkListResponse
 */
export type HomeworkListResponse = Message<"yeying.api.apps.zuoyepigai.HomeworkListResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.apps.zuoyepigai.HomeworkListResponseBody body = 2;
   */
  body?: HomeworkListResponseBody;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.HomeworkListResponse.
 * Use `create(HomeworkListResponseSchema)` to create a new message.
 */
export const HomeworkListResponseSchema: GenMessage<HomeworkListResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_homework, 2);

/**
 * @generated from message yeying.api.apps.zuoyepigai.HomeworkListResponseBody
 */
export type HomeworkListResponseBody = Message<"yeying.api.apps.zuoyepigai.HomeworkListResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;

  /**
   * repeated 表示 List
   *
   * @generated from field: repeated yeying.api.apps.zuoyepigai.HomeworkMetadata list = 2;
   */
  list: HomeworkMetadata[];
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.HomeworkListResponseBody.
 * Use `create(HomeworkListResponseBodySchema)` to create a new message.
 */
export const HomeworkListResponseBodySchema: GenMessage<HomeworkListResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_homework, 3);

/**
 * @generated from message yeying.api.apps.zuoyepigai.HomeworkMetadata
 */
export type HomeworkMetadata = Message<"yeying.api.apps.zuoyepigai.HomeworkMetadata"> & {
  /**
   * 主键标识
   *
   * @generated from field: string uid = 1;
   */
  uid: string;

  /**
   * 用户Id
   *
   * @generated from field: string did = 2;
   */
  did: string;

  /**
   * 科目
   *
   * @generated from field: string subject = 3;
   */
  subject: string;

  /**
   * 试卷Uid
   *
   * @generated from field: string testPaperUid = 4;
   */
  testPaperUid: string;

  /**
   * 创建时间
   *
   * @generated from field: int64 createdAt = 5;
   */
  createdAt: bigint;

  /**
   * 修改时间
   *
   * @generated from field: int64 updatedAt = 6;
   */
  updatedAt: bigint;

  /**
   * 是否删除
   *
   * @generated from field: bool isDeleted = 7;
   */
  isDeleted: boolean;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.HomeworkMetadata.
 * Use `create(HomeworkMetadataSchema)` to create a new message.
 */
export const HomeworkMetadataSchema: GenMessage<HomeworkMetadata> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_homework, 4);

/**
 * 详情
 *
 * @generated from message yeying.api.apps.zuoyepigai.HomeworkDetailRequest
 */
export type HomeworkDetailRequest = Message<"yeying.api.apps.zuoyepigai.HomeworkDetailRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.apps.zuoyepigai.HomeworkDetailRequestBody body = 2;
   */
  body?: HomeworkDetailRequestBody;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.HomeworkDetailRequest.
 * Use `create(HomeworkDetailRequestSchema)` to create a new message.
 */
export const HomeworkDetailRequestSchema: GenMessage<HomeworkDetailRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_homework, 5);

/**
 * @generated from message yeying.api.apps.zuoyepigai.HomeworkDetailRequestBody
 */
export type HomeworkDetailRequestBody = Message<"yeying.api.apps.zuoyepigai.HomeworkDetailRequestBody"> & {
  /**
   * @generated from field: string uid = 1;
   */
  uid: string;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.HomeworkDetailRequestBody.
 * Use `create(HomeworkDetailRequestBodySchema)` to create a new message.
 */
export const HomeworkDetailRequestBodySchema: GenMessage<HomeworkDetailRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_homework, 6);

/**
 * @generated from message yeying.api.apps.zuoyepigai.HomeworkDetailResponse
 */
export type HomeworkDetailResponse = Message<"yeying.api.apps.zuoyepigai.HomeworkDetailResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.apps.zuoyepigai.HomeworkDetailResponseBody body = 2;
   */
  body?: HomeworkDetailResponseBody;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.HomeworkDetailResponse.
 * Use `create(HomeworkDetailResponseSchema)` to create a new message.
 */
export const HomeworkDetailResponseSchema: GenMessage<HomeworkDetailResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_homework, 7);

/**
 * @generated from message yeying.api.apps.zuoyepigai.HomeworkDetailResponseBody
 */
export type HomeworkDetailResponseBody = Message<"yeying.api.apps.zuoyepigai.HomeworkDetailResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;

  /**
   * @generated from field: yeying.api.apps.zuoyepigai.HomeworkMetadata meta = 2;
   */
  meta?: HomeworkMetadata;
};

/**
 * Describes the message yeying.api.apps.zuoyepigai.HomeworkDetailResponseBody.
 * Use `create(HomeworkDetailResponseBodySchema)` to create a new message.
 */
export const HomeworkDetailResponseBodySchema: GenMessage<HomeworkDetailResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_apps_zuoyepigai_homework, 8);

/**
 * *
 * 作业管理
 * 对应 DB 表： zuoyepigai.school_assignment
 *
 * @generated from service yeying.api.apps.zuoyepigai.Homework
 */
export const Homework: GenService<{
  /**
   * 列表
   *
   * @generated from rpc yeying.api.apps.zuoyepigai.Homework.List
   */
  list: {
    methodKind: "unary";
    input: typeof HomeworkListRequestSchema;
    output: typeof HomeworkListResponseSchema;
  },
  /**
   * 详情
   *
   * @generated from rpc yeying.api.apps.zuoyepigai.Homework.Detail
   */
  detail: {
    methodKind: "unary";
    input: typeof HomeworkDetailRequestSchema;
    output: typeof HomeworkDetailResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_yeying_api_apps_zuoyepigai_homework, 0);

