// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file yeying/api/apps/zuoyepigai/imagecontent.proto (package yeying.api.apps.zuoyepigai, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file yeying/api/apps/zuoyepigai/imagecontent.proto.
 */
export const file_yeying_api_apps_zuoyepigai_imagecontent: GenFile = /*@__PURE__*/
  fileDesc("Ci15ZXlpbmcvYXBpL2FwcHMvenVveWVwaWdhaS9pbWFnZWNvbnRlbnQucHJvdG8SGnlleWluZy5hcGkuYXBwcy56dW95ZXBpZ2FpKjgKFEltYWdlQ29udGVudFR5cGVFbnVtEgwKCFFVRVNUSU9OEAASCgoGQU5TV0VSEAESBgoCUUEQAkIcWhp5ZXlpbmcvYXBpL2FwcHMvenVveWVwaWdhaWIGcHJvdG8z");

/**
 * *
 * 图片内容类型
 *
 * @generated from enum yeying.api.apps.zuoyepigai.ImageContentTypeEnum
 */
export enum ImageContentTypeEnum {
  /**
   * *
   * 题目
   *
   * @generated from enum value: QUESTION = 0;
   */
  QUESTION = 0,

  /**
   * *
   * 答案
   *
   * @generated from enum value: ANSWER = 1;
   */
  ANSWER = 1,

  /**
   * *
   * 题目和答案
   *
   * @generated from enum value: QA = 2;
   */
  QA = 2,
}

/**
 * Describes the enum yeying.api.apps.zuoyepigai.ImageContentTypeEnum.
 */
export const ImageContentTypeEnumSchema: GenEnum<ImageContentTypeEnum> = /*@__PURE__*/
  enumDesc(file_yeying_api_apps_zuoyepigai_imagecontent, 0);

